# Generated by Django 5.2.4 on 2026-03-20 19:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['assessment_id']},
        ),
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code', 'course_name']},
        ),
        migrations.AlterModelOptions(
            name='courseallocation',
            options={'ordering': ['allocation_id', 'teacher_id', 'semester_id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['enrollment_id', 'student_id', 'allocation_id']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['employee_id', 'department_id', 'designation']},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['starting_time']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['person_id', 'first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['program_id']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['semester_id', 'status']},
        ),
        migrations.AlterModelOptions(
            name='semesterdetails',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id', 'class_id', 'admission_date']},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(choices=[('hod_change', 'HOD Change'), ('faculty_delete', 'Faculty Delete'), ('student_delete', 'Student Delete'), ('result_calculation', 'Result Calculation')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='session',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], db_index=True, default='Inactive', max_length=9),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Lab Engineer', 'Lab Engineer'), ('Lecturer', 'Lecturer'), ('Senior Lecturer', 'Senior Lecturer'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='institutional_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], db_index=True, default='Inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dropped', 'Dropped'), ('Frozen', 'Frozen'), ('Graduated', 'Graduated'), ('On Probation', 'On Probation')], db_column='status', db_index=True, default='Active', max_length=12),
        ),
    ]
