from django.contrib import admin

from .models import *
admin.site.register(Department)
admin.site.register(Program)
admin.site.register(Class)
admin.site.register(Course)
admin.site.register(Semester)
admin.site.register(SemesterDetails)
admin.site.register(Person)
admin.site.register(Admin)
admin.site.register(Faculty)
admin.site.register(Student)
admin.site.register(Address)
admin.site.register(Qualification)
admin.site.register(AuditTrail)
admin.site.register(CourseAllocation)
admin.site.register(Enrollment)
admin.site.register(Result)
admin.site.register(Transcript)
admin.site.register(Attendance)
admin.site.register(Lecture)
admin.site.register(Assessment)
admin.site.register(AssessmentChecked)
admin.site.register(ChangeRequest)
admin.site.register(Reviews)